# Generated by Django 4.0.6 on 2022-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0002_remove_news_photo_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
