# Generated by Django 4.0.6 on 2022-11-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
