# Generated by Django 4.0.6 on 2022-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
